### ISSUE TITLE
Comparison with unity-atom?

### ISSUE THREAD

**Issue by muhajirdev** [kadinche/Kassets#21]
Hello, awesome package. How is this package different compared to unity-atom's https://unity-atoms.github.io/unity-atoms/tutorials/unirx ?

I purely just trying to learn, no other intention. Thank you

**Comment by ripandy** [comment]
Hello, thanks for the question.

First, to answer your question.

> Hello, awesome package. How is this package different compared to unity-atom's https://unity-atoms.github.io/unity-atoms/tutorials/unirx ?

At a glance, It is completely similar as it just "exposes" `IObservable` by returning them using a method. The rest of the usage is UniRx. So, after calling `_health.ObserveChange()` (or `_health.AsObservable()` in Kassets), you would basically using UniRx.

Additionally in Kassets, if you had UniRx installed without UniTask, you can simplify calls since Kassets Events and Variables implements `IObservable` internally.

You can do 
`_health.Subscribe(UpdateHealth)` 
instead of 
`_health.AsObservable().Subscribe(UpdateHealth)`

Please, see [here](https://github.com/kadinche/Kassets#reactive-with-unirx) as reference.

--- Additional comments from here ---

I knew Unity Atoms, had tried using them before, and I'd still take some peek for references.
It was great if I could say personally, packed with so many advanced features.
But it gets complex quite easily as it had nested ScriptableObject references (SO references another SO).
I was just trying to simplify with Kassets.

Other differences that I could thought of includes :
- Integrates with UniTask (similar to UniRx integration), in which you can use async/await.
- Variables is derived from GameEvents, meaning you can have a Variable and treat them as GameEvent.
- Advanced usage is RequestResponseEvents where you request for a response value.
-- i.e. : `int responseValue = await _intRequestResponseEvent.RequestAsync(0);`

p.s. Sorry for the lack of documentation.

**Comment by ripandy** [comment]
Closing old issue.
Feel free to reopen for further discussion.
