### ISSUE TITLE
How can a single "float variable" be used for multiple objects?

### ISSUE THREAD

**Issue by hasanyalmanbas** [kadinche/Kassets#27]
I created a "health float variable." I will store the health values of the enemies here. Should I create a "health float variable" object for each enemy?

**Comment by ripandy** [comment]
Hello.
Thanks for the question.

I am quite aware of the cons of Scriptable Object Architecture in handling instanced objects like enemies. I once tried to forcefully use them for such case, and it doesn't end very well. It just adds unnecessary complexity to the code base. My default suggestion would be to use simple MonoBehavior/Prefabs for instanced objects.

If you would still wonder on using Scriptable Object Architecture for instanced objects, here are my few suggestions.

- Unless the enemies are not spawn based or single enemy, I'd suggest to use the Health Float Variable as a blueprint for each enemy. The spawned enemy reference to the Health Float Variable as its initial health, then manages its own health afterwards. As a caution, do not change the Health Float Variable, as it would change the initial health for other enemies.
- Use `FloatCollection` instead of `FloatVariable`. As you instantiate an Enemy, add their health to the Collection, so you can observe each enemies' health values through the Scriptable Object. However, you would still need to have the "Initial health value" from elsewhere, whether FloatVariable or MonoBehavior.
- Instatiate the "Health Float Variable" at runtime. Just like Prefabs, a Scriptable Object asset can be instantiated at runtime. However, this instantiated SO are only available at runtime, and cannot be modified through editor like its asset version.

If I got the time, I'll try to create a Sample on handling instanced objects with Kassets. But, due to the time concerns, I can't promise it to be soon.

**Comment by hasanyalmanbas** [comment]
> Hello.
> Thanks for the question.
> 
> I am quite aware of the cons of Scriptable Object Architecture in handling instanced objects like enemies. I once tried to forcefully use them for such case, and it doesn't end very well. It just adds unnecessary complexity to the code base. My default suggestion would be to use simple MonoBehavior/Prefabs for instanced objects.
> 
> If you would still wonder on using Scriptable Object Architecture for instanced objects, here are my few suggestions.
> 
> - Unless the enemies are not spawn based or single enemy, I'd suggest to use the Health Float Variable as a blueprint for each enemy. The spawned enemy reference to the Health Float Variable as its initial health, then manages its own health afterwards. As a caution, do not change the Health Float Variable, as it would change the initial health for other enemies.
> - Use `FloatCollection` instead of `FloatVariable`. As you instantiate an Enemy, add their health to the Collection, so you can observe each enemies' health values through the Scriptable Object. However, you would still need to have the "Initial health value" from elsewhere, whether FloatVariable or MonoBehavior.
> - Instatiate the "Health Float Variable" at runtime. Just like Prefabs, a Scriptable Object asset can be instantiated at runtime. However, this instantiated SO are only available at runtime, and cannot be modified through editor like its asset version.
> 
> If I got the time, I'll try to create a Sample on handling instanced objects with Kassets. But, due to the time concerns, I can't promise it to be soon.

Thank you for your suggestions. I had already planned something similar, but my project involves enemy spawning. If I find an optimal solution, I will get back to you. Thank you for your response.

**Comment by ripandy** [comment]
Closing old issue.
Feel free to reopen for further discussion.
