### ISSUE TITLE
Send null event when subscribe a R3 event

### ISSUE THREAD

**Issue by ruonanzh** [kadinche/Kassets#32]
Hey I got some problem when I subscribe an event.

It will immediately call observer function with an null augment for Push base event.

I am using Kasset 2.7.1 with both R3 and Unitask.

Is there a way to add Raise On Subscribe option, so I can control if raise event on subscribe.

Thanks.

**Comment by ripandy** [comment]
> Is there a way to add Raise On Subscribe option, so I can control if raise event on subscribe.

I assume that you would like to have an Event to be Raised on Subscribe.

As far as I know, you can do that by using pull-based event. 
Pull-based will "Pull" the event on Subscribe. This might work like intended.
Since you import both R3 and UniTask, you can either set event to be pull-based from the inspector, or do conversion using `ToUniTaskAsyncEnumerable()` then do Subscribe from there (note: you will have to add `Cysharp.Threading.Tasks.Linq`).

i.e.
```
using Cysharp.Threading.Tasks.Linq;

...

gameEvent.ToUniTaskAsyncEnumerable().Subscribe( ... );
```

On the other hand, Push-based would not do anything until getting a "Push".
If using Push-based is a must, logically, you will have to Raise an Event somewhere right after Subscription.

If this doesn't solve your intention, I will try to look for another way (Can't promise the time though).
Please let me know.

Thank you!

**Comment by ruonanzh** [comment]
Thank you, for explaination.

After some tests, I noticed for Pull base Event it will be raised on Subscribe and also it will be raised as well when this Event is raised (Which is a little confused for me, becase I think most Pull operation will only get raised when a Pull funtion is called). So can I say, the difference between Pull and Push Event, from the user's prospactive, is wheather raised on subscribe?

More over, If I use Variable or Collection, it will raised on subscribe no matter it is Push or Pull,  is it work as intended?

Thanks you

PS:  I like Kasset, it is a must installed plugin for every project I am working on right now.

**Comment by ripandy** [comment]
> PS: I like Kasset, it is a must installed plugin for every project I am working on right now.

Thank you very much! I appreciate it.
I'm closing this issue now, but feel free to reopen if you'd like further discussion.
